resolver: lts-16.18
packages:
- .
extra-deps:
- natural-transformation-0.4
- git: https://github.com/pkamenarsky/replica.git
  commit: 4e7b83bdca01045f7e087dd638ac5e3be4e8d41a
flags: {}
extra-package-dbs: []
