resolver: lts-13.19
packages:
- .
extra-deps:
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
- git: https://github.com/seagreen/replica.git
  commit: fcb927ecc87d2c405cfb884a024fd54b4bbe489f
- git: https://github.com/pkamenarsky/concur.git
  commit: 6c6bcc07b2688182945b28f154a013eee3f624c5
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
