resolver: lts-13.19
packages:
- .
extra-deps:
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
- git: https://github.com/seagreen/replica.git
  commit: fcf6f06bce4582277e21e398e40762b2957a373d
- git: https://github.com/pkamenarsky/concur.git
  commit: 6c6bcc07b2688182945b28f154a013eee3f624c5
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
