version: 2
jobs:
  build-16.18:
    docker:
      - image: fpco/stack-build:lts-16.18

    working_directory: /home/stackage/src

    steps:
      - checkout
      - restore_cache:
          key: v1-cache-8.6.4-stack-work-{{checksum "stack.yaml"}}-{{checksum "package.yaml"}}
      - run: stack setup
      - run: stack install --test
      - save_cache:
          key: v1-cache-8.6.4-stack-work-{{checksum "stack.yaml"}}-{{checksum "package.yaml"}}
          paths:
            - /root/.stack
            - /home/stackage/src/.stack-work
      - store_test_results:
          path: /home/stackage/src/.stack-work/logs
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-16.18